server:
  port: 8762


spring:
  zipkin:
    base-url: http://localhost:9411

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
feign:
  hystrix:
    enabled: true
    
foo: user-foo version 4
